In [1]:
#1. What is a Python library? Why ^o we use Python libraries?

In [2]:
"""
A Python library is a collection of pre-written code and functions that 
are bundled together for reuse by developers. These libraries are designed 
to provide a set of tools and functionality to help developers solve 
common problems, perform specific tasks, or implement certain features in
their Python programs. Libraries can be written in Python or in other 
languages but accessible from Python through interfaces.


"""

'\nA Python library is a collection of pre-written code and functions that \nare bundled together for reuse by developers. These libraries are designed \nto provide a set of tools and functionality to help developers solve \ncommon problems, perform specific tasks, or implement certain features in\ntheir Python programs. Libraries can be written in Python or in other \nlanguages but accessible from Python through interfaces.\n\n\n'

In [3]:
#2. What is the difference between Numpy array and List?

In [4]:
"""
Type of Elements:

List: A Python list can contain elements of different data types, 
      including integers, floats, strings, or even other lists.
NumPy Array: NumPy arrays are homogeneous, meaning that all elements must 
            be of the same data type. This homogeneity allows for more 
            efficient storage and operations.

Performance:
List: Lists are generally more flexible but may be less efficient for 
      numerical operations due to their dynamic typing and lack of pre-compiled operations.
NumPy Array: NumPy arrays are more efficient for numerical and 
            mathematical operations. They are implemented in C and allow for vectorized operations, which can significantly improve performance for large datasets.

Memory Usage:
List: Lists can be less memory-efficient because they store additional 
      information (like data type and reference count) for each element.
NumPy Array: NumPy arrays are more memory-efficient as they store elements
            in a contiguous block of memory without the overhead of 
            per-element information.

Syntax and Usage:
List: Lists are part of the core Python language and have a more 
     straightforward syntax for simple data structures.
NumPy Array: NumPy provides a specialized array object with its own set of
            functions and methods optimized for numerical operations. It 
            introduces a more sophisticated syntax for array manipulation.

Functionality:
List: Lists offer a basic set of operations for general-purpose use.
NumPy Array: NumPy arrays provide a wide range of mathematical and logical
functions that are essential for numerical computing, making them well-suited
for tasks like linear algebra, statistical analysis, and signal processing.

"""

# Using a list
python_list = [1, 2, 3]
python_list + python_list  # Concatenation, not element-wise addition

# Using a NumPy array
import numpy as np
numpy_array = np.array([1, 2, 3])
numpy_array + numpy_array  # Element-wise addition


array([2, 4, 6])

In [17]:
"""3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("array shape :",arr1.shape)
print("array size :", arr1.size)
print("array dimension :",arr1.ndim)


array shape : (3, 4)
array size : 12
array dimension : 2


In [24]:
"""
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

"""
import numpy as np
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("first row of array :",arr2[0:1])

first row of array : [[1 2 3 4]]


In [30]:
"""
5. How do you access the element at the third row and fourth column from 
the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

"""

import numpy as np
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("third row and fourth column :", arr3[2,3])

third row and fourth column : 12


In [39]:
"""
6. Write code to extract all odd-indexed elements from the given numpy 
array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

"""

import numpy as np

# Given NumPy array
my_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Extracting all odd-indexed elements
odd_indexed_elements = my_array[::, 1::2]

print(odd_indexed_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [45]:
"""
7. How can you generate a random 3x3 matrix with values between 0 and 1?
"""
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print(random_matrix)


[[0.23978434 0.56036614 0.27431782]
 [0.41018929 0.69477701 0.99282991]
 [0.66470456 0.54116307 0.82347784]]


In [48]:
"""
8. Describe the difference between np.random.rand and np.random.randn?

"""
"""
np.random.rand:

Generates random numbers from a uniform distribution over the interval [0, 1).
Takes dimensions as separate arguments rather than a tuple.
Returns an array with specified dimensions, where each element is a random
number between 0 (inclusive) and 1 (exclusive).
"""
import numpy as np

# Generate a 2x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(2, 3)
print(random_matrix)
"""
np.random.randn:

Generates random numbers from a standard normal distribution (mean 0, 
standard deviation 1).
Takes dimensions as separate arguments rather than a tuple.
Returns an array with specified dimensions, where each element is a 
random number sampled from a standard normal distribution.

"""
import numpy as np

# Generate a 2x3 matrix with random values from a standard normal distribution
random_matrix_standard_normal = np.random.randn(2, 3)
print(random_matrix_standard_normal)

[[0.04383842 0.50302285 0.89714636]
 [0.10440112 0.19029498 0.42140485]]
[[-1.84614519  0.45525244  1.82812516]
 [ 0.14601647  0.03579727  0.25261079]]


In [49]:
"""
9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

"""

import numpy as np

# Given array
original_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Increase the dimension along a new axis (axis=2 in this example)
increased_dimension_array = original_array[:, :, np.newaxis]

print("Original Array:")
print(original_array)
print("\nArray with Increased Dimension:")
print(increased_dimension_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [54]:
"""
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

"""
arr10 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("transpose :")
print(arr10.T)

transpose :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [64]:
"""
11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1. Index wiLe multiplication
2. Matix multiplication
3. Add both the maticK
4. Subtact matix B om 
5. Divide Matix B by A
"""
a2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("1. Index whiLe multiplication")
print(a2*b2)
print("2. Matrix multiplication")
print(a2 @ b2.T)
print("3. Add both the matix")
print(a2 + b2)
print("4. substract B from A")
print(a2-b2)
print("5. divid Matrix B by A")
print(a2/b2)


1. Index whiLe multiplication
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
2. Matrix multiplication
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
3. Add both the matix
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
4. substract B from A
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
5. divid Matrix B by A
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [65]:
"""
12. Which function in Numpy can be used to swap the byte order of an array?
"""
"""
The function np.ndarray.byteswap() in NumPy can be used to swap the byte 
order of an array. It swaps the byte order of the array elements in place. Here's an example:
"""
import numpy as np

# Create an array with integers
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap byte order
swapped_array = original_array.byteswap()

print("Original Array:")
print(original_array)
print("\nArray after Byte Swapping:")
print(swapped_array)


Original Array:
[1 2 3 4]

Array after Byte Swapping:
[16777216 33554432 50331648 67108864]


In [66]:
"""
13. What is the significance of the np.linalg.inv function?
"""
"""
The np.linalg.inv function in NumPy is used to compute the 
(multiplicative) inverse of a matrix. For a square matrix A, the inverse 
matrix A_inv is such that A @ A_inv = A_inv @ A = I, where I is the 
identity matrix. This function is significant in linear algebra and is 
often used to solve systems of linear equations, among other applications.


"""
import numpy as np

# Define a 2x2 matrix
matrix_a = np.array([[2, 1],
                    [7, 4]])

# Compute the inverse of the matrix
matrix_a_inv = np.linalg.inv(matrix_a)

print("Original Matrix:")
print(matrix_a)
print("\nInverse Matrix:")
print(matrix_a_inv)


Original Matrix:
[[2 1]
 [7 4]]

Inverse Matrix:
[[ 4. -1.]
 [-7.  2.]]


In [ ]:
"""
14. What does the np.reshape function do, and how is it used?
"""

"""
The np.reshape function is used to change the shape of an array without 
changing its data. It returns a new array with the specified shape. The 
function takes the desired shape as an argument. Here's an example:
"""
import numpy as np

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2D array with 2 rows and 3 columns
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)
print("\nReshaped Array:")
print(reshaped_array)


In [ ]:
"""
15. What is broadcasting in Numpy?
"""

"""
Broadcasting is a powerful feature in NumPy that allows operations 
between arrays of different shapes and sizes. NumPy automatically 
broadcasts the smaller array to match the shape of the larger array, 
making element-wise operations possible without the need for explicit 
looping.

"""

import numpy as np

# Create a 2x3 matrix
matrix_a = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Add a scalar to each element using broadcasting
result = matrix_a + 10

print("Original Matrix:")
print(matrix_a)
print("\nResult after Broadcasting:")
print(result)
